# Generated by Django 4.2.6 on 2024-02-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_companies"),
        ("purchases", "0001_add_product_material_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_paid_by_card", models.BooleanField(verbose_name="paid by card")),
            ],
            options={
                "verbose_name": "purchase",
                "verbose_name_plural": "purchases",
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="PurchaseProcedure",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived", models.DateTimeField(blank=True, null=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_procedures",
                        to="companies.procedure",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_procedures",
                        to="purchases.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase of procedure",
                "verbose_name_plural": "purchase of procedures",
                "ordering": ("purchase", "procedure"),
            },
        ),
    ]
