# Generated by Django 4.2.6 on 2024-02-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_companies"),
        ("purchases", "0002_purchases"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsedMaterial",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("archived", models.DateTimeField(blank=True, null=True)),
                ("amount", models.PositiveIntegerField(verbose_name="amount")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_materials",
                        to="companies.stockmaterial",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_materials",
                        to="purchases.purchaseprocedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "used material",
                "verbose_name_plural": "used materials",
                "ordering": ("material", "procedure"),
            },
        ),
    ]
