# Generated by Django 4.2.6 on 2024-02-21 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_companies"),
        ("purchases", "0003_used_material"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usedmaterial",
            unique_together={("material", "procedure")},
        ),
    ]
