repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: "bash ./.git/hooks/black.sh"
        language: system
        types: [python]
        args: [--line-length=100, --all-files]

      - id: tests
        name: Run tests
        entry: "bash ./.git/hooks/tests.sh"
        language: system
        verbose: true
