# Generated by Django 4.2.6 on 2023-12-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="department name")),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand", models.CharField(max_length=255, verbose_name="material brand")),
                ("name", models.CharField(max_length=255, verbose_name="material name")),
                ("unit", models.CharField(max_length=255, verbose_name="material unit")),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materials",
            },
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="material type name")),
            ],
            options={
                "verbose_name": "material type",
                "verbose_name_plural": "material types",
            },
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("address", models.CharField(max_length=255, verbose_name="point address")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="points", to="companies.company"
                    ),
                ),
            ],
            options={
                "verbose_name": "point",
                "verbose_name_plural": "points",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="stock date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("progress", "progress"),
                            ("done", "done"),
                            ("canceled", "canceled"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="stock status",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="stocks", to="companies.point"
                    ),
                ),
            ],
            options={
                "verbose_name": "stock",
                "verbose_name_plural": "stocks",
            },
        ),
        migrations.CreateModel(
            name="StockMaterial",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="material price")),
                ("quantity", models.IntegerField(verbose_name="material quantity")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_materials",
                        to="companies.material",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="materials", to="companies.stock"
                    ),
                ),
            ],
            options={
                "verbose_name": "stock material",
                "verbose_name_plural": "stock materials",
            },
        ),
        migrations.AddField(
            model_name="material",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="materials", to="companies.materialtype"
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("position", models.CharField(max_length=255, verbose_name="employee position")),
                ("fire_date", models.DateField(blank=True, null=True, verbose_name="employee fire date")),
                ("departments", models.ManyToManyField(related_name="employees", to="companies.department")),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
            },
        ),
    ]
