# Generated by Django 4.2.6 on 2023-12-22 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_init"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"ordering": ["-date"], "verbose_name": "stock", "verbose_name_plural": "stocks"},
        ),
    ]
