# Generated by Django 4.2.6 on 2023-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_add_employee_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="employee",
            name="departments",
        ),
        migrations.AddField(
            model_name="employee",
            name="departments",
            field=models.ManyToManyField(related_name="employees", to="companies.department"),
        ),
    ]
