# Generated by Django 4.2.6 on 2023-10-09 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("address", models.CharField(max_length=255, verbose_name="point address")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="points", to="companies.company"
                    ),
                ),
            ],
            options={
                "verbose_name": "point",
                "verbose_name_plural": "points",
            },
        ),
    ]
