# Generated by Django 4.2.6 on 2023-10-10 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_point_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="point",
            options={"ordering": ("id",), "verbose_name": "point", "verbose_name_plural": "points"},
        ),
    ]
