# Generated by Django 4.2.6 on 2023-11-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_fk_to_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="fire_date",
            field=models.DateField(blank=True, null=True, verbose_name="employee fire date"),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.CharField(default="test", max_length=255, verbose_name="employee position"),
            preserve_default=False,
        ),
    ]
