# Generated by Django 4.2.6 on 2024-01-26 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_companies"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterProcedure",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("price", models.PositiveIntegerField(verbose_name="procedure price")),
                (
                    "coef",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="coefficient",
                    ),
                ),
                ("archived", models.BooleanField(default=False, verbose_name="archived")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="employees", to="companies.employee"
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="procedures", to="companies.procedure"
                    ),
                ),
            ],
            options={
                "verbose_name": "procedure master",
                "verbose_name_plural": "procedure masters",
            },
        ),
    ]
