# Generated by Django 4.2.6 on 2024-01-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_companies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="procedure category name")),
            ],
            options={
                "verbose_name": "procedure category",
                "verbose_name_plural": "categories of procedures",
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="procedure",
            name="kind",
        ),
        migrations.AddField(
            model_name="procedure",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedures",
                to="companies.category",
                verbose_name="procedure category",
            ),
            preserve_default=False,
        ),
    ]
