# Generated by Django 4.2.6 on 2023-12-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_upd_empl_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand", models.CharField(max_length=255, verbose_name="material brand")),
                ("name", models.CharField(max_length=255, verbose_name="material name")),
                ("unit", models.CharField(max_length=255, verbose_name="material unit")),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materials",
            },
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="material type name")),
            ],
            options={
                "verbose_name": "material type",
                "verbose_name_plural": "material types",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="stock date")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("open", "open"), ("closed", "closed")],
                        default="draft",
                        max_length=10,
                        verbose_name="stock status",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="stocks", to="companies.point"
                    ),
                ),
            ],
            options={
                "verbose_name": "stock",
                "verbose_name_plural": "stocks",
            },
        ),
        migrations.CreateModel(
            name="StockMaterial",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="material price")),
                ("quantity", models.IntegerField(verbose_name="material quantity")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_materials",
                        to="companies.material",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="materials", to="companies.stock"
                    ),
                ),
            ],
            options={
                "verbose_name": "stock material",
                "verbose_name_plural": "stock materials",
            },
        ),
        migrations.AddField(
            model_name="material",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="materials", to="companies.materialtype"
            ),
        ),
    ]
