# Generated by Django 4.2.6 on 2023-12-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_stock_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="status",
            field=models.CharField(
                choices=[("draft", "draft"), ("progress", "progress"), ("done", "done"), ("canceled", "canceled")],
                default="draft",
                max_length=10,
                verbose_name="stock status",
            ),
        ),
    ]
