# Generated by Django 4.2.6 on 2024-01-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_companies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterprocedure",
            name="archived",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
