# Generated by Django 4.2.6 on 2024-02-09 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_companies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ("fire_date",), "verbose_name": "employee", "verbose_name_plural": "employees"},
        ),
        migrations.AlterModelOptions(
            name="masterprocedure",
            options={
                "ordering": ("employee", "procedure"),
                "verbose_name": "procedure master",
                "verbose_name_plural": "procedure masters",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ("kind", "name"), "verbose_name": "material", "verbose_name_plural": "materials"},
        ),
        migrations.AlterModelOptions(
            name="materialtype",
            options={"ordering": ("name",), "verbose_name": "material type", "verbose_name_plural": "material types"},
        ),
        migrations.AlterModelOptions(
            name="point",
            options={"ordering": ("company",), "verbose_name": "point", "verbose_name_plural": "points"},
        ),
        migrations.AlterModelOptions(
            name="stockmaterial",
            options={
                "ordering": ("stock", "material"),
                "verbose_name": "stock material",
                "verbose_name_plural": "stock materials",
            },
        ),
    ]
