# Generated by Django 4.1.5 on 2023-02-12 19:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(old_name='CompanyModel', new_name='Company',),
    ]
