# Generated by Django 4.1.5 on 2023-02-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_companymodel_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPoint',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('address', models.CharField(max_length=255)),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='points',
                        to='companies.company',
                    ),
                ),
            ],
        ),
    ]
