# Generated by Django 4.1.5 on 2023-02-04 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companiesmodel_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companiesmodel',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='companiesmodel',
            name='time_created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companiesmodel',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
