pytest_plugins = [
    "app.factory",
    "app.fixtures",
    "a12n.factory",
    "a12n.fixtures",
    "users.factory",
    "users.fixtures",
    "companies.company_factory",
    "companies.department_factory",
    "companies.employee_factory",
    "companies.stock_factory",
    "companies.company_fixtures",
    "companies.department_fixtures",
    "companies.employee_fixtures",
    "companies.stock_fixtures",
]
